# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.define "zookeeper" do |zookeeper|
    zookeeper.vm.hostname = "zookeeper"

    zookeeper.vm.network "private_network", ip: "192.168.10.100"

    # default router
    # zookeeper.vm.provision "shell",
    #   run: "always",
    #   inline: "route add default gw 192.168.0.1"
    #
    # # default router ipv6
    # zookeeper.vm.provision "shell",
    #   run: "always",
    #   inline: "route -A inet6 add default gw fc00::1 eth1"
    #
    # # delete default gw on eth0
    # zookeeper.vm.provision "shell",
    #   run: "always",
    #   inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "zookeeper"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/hashicorp/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
  end
end