receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  jaeger:
    endpoint: 'jaeger-collector:14250'
    # Exporters are set to secure by default and require tls certs for connections
    insecure: true

processors:
  batch:

service:
  pipelines: # section that can contain multiple subsections, one per pipeline
    traces: # type of the pipeline
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
