---
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*(tests/|Dockerfile.j2).*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: linting/.eslintrc.js
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          # Disable Kubeval linting as manifest files with CRDs as these fail
          # validation due to missing JSON schemas. Kubeval supports disabling the
          # schema check, but super-linter does not support passing flags for linters
          # https://github.com/github/super-linter/issues/891
          # https://github.com/github/super-linter/issues/987
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_ANSIBLE: false
          VALIDATE_BASH: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_JAVA: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSON: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_TYPESCRIPT_STANDARD: false
